global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<host-email-id>'
  smtp_auth_username: '<host-email-id>'
  smtp_auth_identity: '<host-email-id>'
  smtp_auth_password: '<app-password>'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: '<recipuent-1>, <recipuent-2>, ...'
      send_resolved: true
