apiVersion: 1

datasources:
  - name: Episilia-Logs
    type: loki
    access: proxy
    orgId: 1
    url: http://${PUBLIC_IP}:9002
    basicAuth: false
    isDefault: true
    editable: false
#  - name: Episilia-Historic-Search
#    type: loki
#    access: proxy
#    orgId: 1
#    url: http://${PUBLIC_IP}:9001
#    basicAuth: false
#    isDefault: false
#    editable: false
  - name: Episilia-Tail
    type: loki
    access: proxy
    orgId: 1
    url: http://${PUBLIC_IP}:9005
    basicAuth: false
    isDefault: false
    editable: false
